
const  E2  =  383


mO  =  {
    "CtSMa": "$cdc_asdjflasutopfhvcZLmcfl_",
    "hDQEL": "idPrefix_",
    "MqDcL": "cache_",
    "DizwW": "nextId_",
    "rONfq": "$chrome_asyncScriptInfo",
    "oRuBk": "webdriver",
    "auXFb": "^cdc_[a-zA-Z0-9]{22}_",
    "kRLYY": "left",
    "fHkJS": "DOMContentLoaded",
    "hgCoa": "addEventListener",
    "LUGNY": "onreadystatechange",
    "IfrAN": "readyState",
    "HHuOD": "style",
    "AdUOZ": "text/css",
    "PuJYY": "head",
    "seLxr": "script",
    "LLNeD": "window.aliyun_csp_inline_test = 1;aliyun_csp_inline_test_func()",
    "Ydskn": "px)",
    "OvcYh": "min-device-width",
    "gCNCX": "min-device-height",
    "lBOhQ": "viewport",
    "inWlh": "initial-scale",
    "zmHHq": "initial-scale=",
    "XzbNk": "_aliyunwaf_test_cookie=test; domain=.",
    "rMNXd": "; path=/",
    "FGWWt": "_aliyunwaf_test_cookie=test",
    "TIqHP": "_aliyunwaf_test_cookie=; domain=.",
    "hrcBG": "; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT",
    "ElEJc": "div",
    "pqffC": "<a></a>",
    "TTAOW": "3|0|4|1|2",
    "Oiqtz": "data:",
    "tQQsJ": "blob:",
    "zKYLx": "4|2|1|0|3",
    "xyDux": "number",
    "QISrS": ";expires=",
    "VsVHn": ";path=/;domain=",
    "ybZQK": "DGi0YA7BemWnQjCl4+bR3f8SKIF9tUz/xhr2oEOgPpac=61ZqwTudLkM5vHyNXsVJ",
    "fGNWx": "aliyun_waf_testLocalStorage",
    "RHigc": "keydown",
    "vnPFM": "1|4|0|3|2",
    "wIQNj": "touchstart",
    "bDKfx": "touches",
    "nBiCI": "changedTouches",
    "YsYmk": "3|0|2|1|5|4",
    "GqUGj": "3|0|2|4|1",
    "xWSRQ": "mousedown",
    "svtNJ": "ssxmod_itna",
    "gaLNh": "ssxmod_itna2",
    "kQdbb": "prototype",
    "gFfSy": "text",
    "QrRmT": "canvas",
    "jQVCP": "inline",
    "zgRPE": "alphabetic",
    "AwNfo": "#f60",
    "Urvli": "#069",
    "TLZKf": "11pt no-real-font-123",
    "Vtnbo": "Cwm fjordbank glyphs vext quiz, 😃",
    "OIGFu": "rgba(102, 204, 0, 0.7)",
    "pHZwR": "18pt Arial",
    "MsfYC": "stack",
    "bZTyu": "__BROWSERTOOLS_DOMEXPLORER_ADDED",
    "nxlSu": "v_console_log",
    "srWEc": "selenium",
    "hKtEd": "Element.prototype.webkitMatchesSelector",
    "Vjztt": "zoom",
    "zWrJW": "resize",
    "bMkPi": "text-rendering",
    "gYKRZ": "text-align-last",
    "QcsAQ": "-webkit-hyphens",
    "kosYY": "11|6|0|5|10|2|7|3|1|4|8|9",
    "fHxek": "PointerEvent",
    "UxPCe": "getCoalescedEvents",
    "fzkqJ": "BudgetService",
    "xgdgf": "getAttributeNames",
    "MVQUu": "performance.timeOrigin",
    "tcJmP": "Intl",
    "JVtTS": "PluralRules",
    "Jpzhm": "getMatchedCSSRules",
    "TuMJs": "PerformanceServerTiming",
    "JSenP": "BigInt",
    "HgwIe": "Symbol",
    "pSUhk": "species",
    "arhfN": "Object",
    "daqON": "values",
    "xDWjQ": "OfflineAudioContext",
    "bElmS": "close",
    "ZGEJy": "Touch",
    "OaVJz": "Proxy",
    "jDlyt": "match",
    "BMKjX": "Reflect",
    "jRjYT": "toPrimitive",
    "fZBrl": "WeakMap",
    "EdRKI": "DOMTokenList",
    "iSDTy": "replace",
    "wDsLn": "hasInstance",
    "alkuj": "isSecureContext",
    "WbUsV": "origin",
    "asLaF": "PerformanceTiming",
    "JYVzI": "secureConnectionStart",
    "lWlYN": "showModalDialog",
    "kOyJq": "HTMLDocument",
    "FeFSX": "getSelection",
    "mocYR": "HTMLMediaElement",
    "EVMlm": "mozAutoplayEnabled",
    "aCsBd": "0|0",
    "bJXzY": "history",
    "BmLat": "webgl",
    "gJItI": "experimental-webgl",
    "vIQAB": "WEBGL_debug_renderer_info",
    "EiSOV": "ns|3",
    "PMycx": "ns|2",
    "lfinS": "ns|1",
    "FBqxX": "ApplePaySession",
    "JdxgP": "ApplePayError",
    "xCWos": "Bluetooth",
    "IOUMH": "BluetoothDevice",
    "whbxk": "BluetoothUUID",
    "UgVZx": "<br>",
    "XychQ": "function",
    "gqWoA": "string",
    "liwgY": "undefined",
    "ILWPE": "-1|0|0|0|0",
    "wOhCe": "__proto__.__proto__",
    "JYFda": "//o.alicdn.com/captcha-frontend/aliyunCaptcha/AliyunCaptcha.js?t=",
    "YLcRI": "//g.alicdn.com/AWSC/AWSC/awsc.js?t=",
    "YvHed": "onload",
    "ZhLrb": "waf_nc_block",
    "fERCP": "body * {pointer-events:auto!important}",
    "yXhtV": "waf-nc-traceid",
    "gatIY": "日志ID: ",
    "lmNun": "TraceID:",
    "JKthr": "block",
    "YaVLT": "https://o.alicdn.com/frontend-lib/captcha-lib/",
    "mhTXm": ".json",
    "UBfXe": "GET",
    "YiYss": "1|0|3|2|5|4",
    "NRgnE": "captchaV2",
    "yaXbd": "SLIDING",
    "XHxaB": "CHECK_BOX",
    "EMRHZ": "3|2|4|0|5|1",
    "caekL": "Top",
    "FXQRg": "center",
    "Bmqtg": "--aliyun-zoom-ratio",
    "zkjtm": "aliyunCaptcha-window-embed",
    "xMeIX": "nocaptcha",
    "eBHRJ": "margin",
    "NvYoT": "验证码初始化失败，请更换网络访问",
    "tcJSN": "captcha-error",
    "OnCFs": "embed",
    "AwdJA": "#nocaptcha",
    "xrjbD": "1.0",
    "fCuFC": "CF_APP_WAF",
    "kiHGe": "register_h5",
    "YftIK": "register",
    "BaQdA": "code100",
    "AVwDI": "default",
    "bxwKM": "aliyunwaf_6a6f5ea8",
    "pfnsH": "_dySig",
    "UbFeN": "true",
    "HvqNG": "0|1|4|6|2|5|3",
    "vvptf": "0|3|6|2|1|5|4",
    "lLPLp": "ANY",
    "tLvdi": "HEAD",
    "ZOUHm": "dySigV2",
    "slFJJ": "jsclg",
    "KYdkX": "captcha",
    "ONNXU": "readystatechange",
    "JyiYZ": "json",
    "TcpTV": "The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json')",
    "FymHR": "abort",
    "odbZx": "error",
    "RnvNz": "load",
    "FURAu": "loadend",
    "juIoE": "loadstart",
    "Auczu": "progress",
    "GPlMb": "timeout",
    "FBruW": "responseType",
    "DfxZh": "response",
    "YZhOX": "responseText",
    "TYFIq": "<textarea\\s+id=\"renderData\"\\s+style=\"display:none\">([\\s\\S]*?)<\\/textarea>",
    "WYjXn": "initAli",
    "diRnC": "yunCaptcha",
    "gbzmK": "window._w",
    "KioHf": "af_is_mobile",
    "OiEqM": "appkey:",
    "jyXbH": " \"CF_APP_WAF\", // 应用",
    "eFNXF": "waf-nc-h5-mask",
    "EBnhA": "acw_s",
    "tUYFo": "c__v2",
    "Yluas": "var arg1",
    "KyRAn": "dySig",
    "MgsdV": "/elopf3z6/ye5kgn3x/d8hdyctz",
    "eUlOl": "_waf_a23a0b772",
    "Crzgr": "var arg1='",
    "HTSLX": "/nfb8ouq4/om6lhs71/109xfjkc",
    "Mmlyn": "0b72f618-4c1-4aba-9a78-f",
    "WzuVF": "return ",
    "wzYTA": "language: \"en\",//语言包，默认中文",
    "NedJg": "language: \"en\", //语言包，默认中文",
    "UJmbe": "1|0|4|3|2",
    "HTgWH": "id=\"traceid\"",
    "nQsXP": "</div>",
    "tBUoe": "xhr",
    "Tlpzr": "Content-Type",
    "SxhWe": "arraybuffer",
    "SOuwQ": "utf-8",
    "kRyCL": "Punish-Type",
    "HvHvS": "aliyun_",
    "GrcmR": "waf_",
    "pohXu": "371ac51ab53",
    "INdsU": "fc53eb6bf9aa462a72e9f",
    "GGSBs": "b63e746d3d0",
    "yYoYv": "f33fa6ce3709868ba5f8b",
    "XfDRK": "sigchl",
    "cdsjI": "var",
    "DEjpI": " _0x2576",
    "tsarM": "duCiQ',",
    "gqvhk": "'MOvsy",
    "Dvnyh": "function r(a",
    "KuFxT": ",J)",
    "AlBHX": "IunBRbfp7MLmwv6AckTt",
    "gTqIC": "iY1jgrHZxGhlzW3aVPqEFN5J",
    "rtAcl": "function e(l",
    "ObdLe": ",m)",
    "pToic": "6l9vPJp1BwS5GC",
    "zHuAy": "Ae8L70NoszbtVcuhx3igmdrFf",
    "qplUs": "_waf_bd8ce2ce37",
    "Aopqd": "_waf_a86dfdc5f2",
    "TxCMh": "[15, 35, 29, 24, 33, 16, 1, 38, 10, 9, 19, 31, 40, 27, 22, 23, 25, 13, 6, 11,39,18,20,8, 14, 21, 32, 26, 2, 30, 7, 4, 17, 5, 3, 28, 34, 37, 12, 36]",
    "mUsAN": "3000176000856006061501533003690027800375",
    "YSWhr": "content-type",
    "ORFaG": "multipart/form-data;",
    "rqKDs": "fetch",
    "rsySh": "same-origin",
    "IpCdq": "text/html",
    "Xkykv": "object",
    "qlBKY": "none",
    "rRxqE": "2.3.8d",
    "ZQkZb": "xdomain",
    "PJGPp": "__00b204e9800998__",
    "wFrSz": "captchaType",
    "CJeTW": "6cc076e6727a87d6",
    "jtCTj": "false",
    "pzzRq": "button",
    "NAOos": "input",
    "PyhyC": "textarea",
    "AoRli": "ontouchstart",
    "xsiCg": "websdk-",
    "MZAxU": "mouseup",
    "NQBbF": "mousemove",
    "hbPMf": "touchmove",
    "ItItP": "touchend",
    "nGvQf": "keyup",
    "rbdeL": "hidden",
    "EZMJv": "visibilitychange",
    "kkawi": "mozHidden",
    "NZwvd": "mozvisibilitychange",
    "ZVTAD": "msHidden",
    "wcicx": "msvisibilitychange",
    "ICGkx": "webkitHidden",
    "gKKCN": "webkitvisibilitychange",
    "rCUwD": "compositionend",
    "Dxopr": "paste",
    "hXxKX": "click",
    "AFKOL": "acw_sc__v2",
    "ugAEV": "acw-sc--v3",
    "cInrm": "acw_sc__v3",
    "JPeKp": "<div id=\"waf_nc_block\" style=\"display: none;\">\n    <div class=\"waf-nc-mask\"></div>\n    <div id=\"WAF_NC_WRAPPER\" class=\"waf-nc-wrapper\">\n        <p class=\"waf-nc-title\">访问验证</p>\n        <p class=\"waf-nc-description\">为保证您的正常访问，请进行如下验证。</p>\n        <p id=\"waf-nc-traceid\" class=\"waf-nc-traceid-class\"></p>\n        <div id=\"nocaptcha\"></div>\n    </div>\n</div>\n</div>",
    "DsDru": "#waf_nc_block * {pointer-events: auto;}\n#waf_nc_block{position:fixed;_position:absolute;width:100%;height:100%;top:0;bottom:0;left:0;z-index:2000000000;}\n#waf_nc_block #aliyunCaptcha-sliding-slider{background:#ff6a00!important}\n#waf_nc_block .aliyunCaptcha-show{margin-left: -24px;}\n#waf_nc_block #aliyunCaptcha-window-embed{margin-bottom: 10px!important}\n#waf_nc_block .waf-nc-mask{background:#000;opacity:.5;filter:alpha(opacity=50);width:100%;height:100%}\n#waf_nc_block .waf-nc-wrapper {min-height: 220px;width: 348px;text-align: center;position: absolute;top: 50%;left: 50%;transform: translate(-50%, -80%);background: #fff;box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.15);}\n#waf_nc_block .waf-nc-title{margin-top:28px;font-size:24px;font-weight:500;color:#181818;letter-spacing:1.71px;text-align:center}\n#waf_nc_block .waf-nc-description{margin-top:24px;margin-left:24px;font-size:14px;color:#666;text-align:left}\n#waf_nc_block .waf-nc-traceid-class{margin-top:8px;margin-left:24px;font-size:12px;color:#999;text-align:left}\n#nocaptcha{margin-left:24px;margin-top:14px}\n#waf_nc_block .nc_bg{background:#fff3ea!important}\n#waf_nc_block .btn_slide{background:#ff6a00!important;border:0!important;color:#fff!important;width:48px!important;height:48px!important;font-size:30px;font-weight:900!important;line-height:48px!important}\n#waf_nc_block .btn_ok{background:#ff6a00!important;border:0!important;color:#fff!important;width:48px!important;height:48px!important;font-size:30px;font-weight:900!important;line-height:48px!important}\n#waf_nc_block .nc_scale{background:rgba(241,241,242,1)!important;height:48px!important}#waf_nc_block .nc-lang-cnt{height:48px!important;margin-left:10px!important;line-height:48px!important;font-size:14px!important}\n#waf_nc_block .sm-pop-inner{position:relative!important}\n#waf_nc_block .captcha-error{margin-left:34px;color:#e00000;font-size:14px;font-weight:400;text-align:center;border-radius:4px;background-color:#ffeaea;width:280px;height:40px;line-height:40px}",
    "mGMGy": "<div id=\"waf_nc_block\" style=\"display: none\">\n    <div class=\"waf-nc-h5-mask\"></div>\n    <div id=\"WAF_NC_WRAPPER\" class=\"waf-nc-h5-wrapper\">\n        <p class=\"waf-nc-title\">访问验证</p>\n        <div class=\"waf-nc-description\">\n            为了您的操作安全，请完成以下验证\n        </div>\n        <p id=\"waf-nc-traceid\" class=\"waf-nc-traceid-class\"></p>\n        <div id=\"nocaptcha\" data-nc-idx=\"1\"></div>\n    </div>\n</div>",
    "QGLRw": "#waf_nc_block * {pointer-events: auto;}\n#waf_nc_block{position:fixed;_position:absolute;width:100%;height:100%;top:0;bottom:0;left:0;z-index:2000000000;}\n#waf_nc_block .waf-nc-h5-mask{background:#000;opacity:.5;filter:alpha(opacity=50);width:100%;height:100%}\n#waf_nc_block #aliyunCaptcha-sliding-wrapper #aliyunCaptcha-sliding-body #aliyunCaptcha-sliding-slider{background:#ff6a00!important;font-size:15px!important}\n#waf_nc_block #aliyunCaptcha-window-embed {margin-bottom: 10px!important;}\n#waf_nc_block #aliyunCaptcha-window-embed * {text-size-adjust: 100% !important;-webkit-text-size-adjust: 100% !important;-ms-text-size-adjust: 100% !important;-moz-text-size-adjust: 100% !important;}\n#waf_nc_block #aliyunCaptcha-sliding-body #aliyunCaptcha-sliding-slider{background:#ff6a00!important;}\n#waf_nc_block #aliyunCaptcha-sliding-wrapper #aliyunCaptcha-sliding-body #aliyunCaptcha-sliding-text-box span {font-size:15px!important}\n#waf_nc_block .waf-nc-h5-wrapper {min-height: 220px;width: 340px;position: absolute;top: 20%;left: 50%;background: #fff;border-radius: 9px;box-sizing: border-box;padding-top: 5%;margin-left: -170px;text-align: center;}\n#waf_nc_block .waf-nc-title{margin-top:1px;font-size:16px;font-weight:500;color:#1a1a1a;text-align:center}#waf_nc_block .waf-nc-description{margin-top:24px;font-size:12px;color:#595959;text-align:center}#waf_nc_block .waf-nc-traceid-class{margin-top:8px;font-size:12px;color:#999;text-align:center}#waf_nc_block .nc_bg{background:#fff3ea!important}#waf_nc_block .btn_slide{background:#ff6a00!important;border:0!important;color:#fff!important;width:48px!important;height:48px!important;font-size:30px;font-weight:900!important;line-height:48px!important}#waf_nc_block .btn_ok{background:#ff6a00!important;border:0!important;color:#fff!important;width:48px!important;height:48px!important;font-size:30px;font-weight:900!important;line-height:48px!important}#waf_nc_block .nc_scale{background:rgba(241,241,242,1)!important;height:48px!important}#waf_nc_block .nc-lang-cnt{height:48px!important;margin-left:10px!important;line-height:48px!important;font-size:14px!important}\n#waf_nc_block .nc_wrapper{margin-left: auto;  margin-right: auto;}\n#waf_nc_block #aliyunCaptcha-checkbox-wrapper #aliyunCaptcha-checkbox-body #aliyunCaptcha-checkbox-left #aliyunCaptcha-checkbox-text-box {font-size:14px!important}\n#waf_nc_block #aliyunCaptcha-checkbox-icon{width:20px!important;height:20px!important}\n#waf_nc_block #aliyunCaptcha-checkbox-wrapper #aliyunCaptcha-captcha-fail,#aliyunCaptcha-captcha-refresh{font-size: 14px!important;}\n#waf_nc_block .aliyunCaptcha-checkbox-icon-checked {width:10px!important;height:5px!important;border-left:2px solid #009431 !important;border-bottom: 2px solid #009431 !important;transform:rotate(-45deg);}\n#waf_nc_block .aliyunCaptcha-loader{font-size:2px!important}\n#waf_nc_block .aliyunCaptcha-loader-icon{width:10px!important;height:10px!important;}\n#waf_nc_block .captcha-error{margin-left:34px;color:#e00000;font-size:14px;font-weight:400;text-align:center;border-radius:4px;background-color:#ffeaea;width:280px;height:40px;line-height:40px}\n",
    "WKiQg": "为保证您的正常访问,请进行如下验证",
    "fgVbI": "访问验证",
    "fRGrx": "Please slide to verify that you're not a robot",
    "Pkjlr": "Access Verification",
    "pnUud": "type__",
    "vtLPD": "refer__",
    "GcrJi": "ipcity__",
    "MxtLJ": "md5__",
    "NSebW": "decode__",
    "PYivJ": "encode__",
    "AjcSs": "time__",
    "fTPBb": "timestamp__",
    "ZKPuN":function(Qf, Qz) {
                return Qf < Qz;
            },
    "TVgzH":function(Qf, Qz) {
                return Qf << Qz;
            },
    'JIcan': function(Qf, Qz) {
                return Qf - Qz;
            },
    'cSrNo': function(Qf, Qz) {
                return Qf + Qz;
            },
    'TgLRG': function(Qf, Qz) {
                return Qf + Qz;
            },

}

ie  =  {
    "m4": 1877,
    "m5": 1975,
    "m6": 493,
    "m7": 1254,
    "m8": 1560,
    "m9": 1888,
    "mm": 2374
}
function X(Qf) {
        var  Qz, QI = -0xfd * 0x3 + -0x35c + 0x4d4 + E2;
        for (Qz = -0x1c81 * 0x1 + -0x136a + -0x1d * -0x1a7; mO['ZKPuN'](Qz, Qf['length']); Qz++)
            QI = mO['TgLRG'](mO['cSrNo'](mO['JIcan'](mO['TVgzH'](QI, 0xc70 + -0x2 * -0x1139 + -0x305a + E2), QI), -0x1 * -0x1aa7 + 0x1fc5 * -0x1 + 0x52d + E2), Qf['charCodeAt'](Qz)),
            QI |= -0x241 * -0xf + 0x1 * 0x1102 + -0x3450 + E2;

        return QI;
    }



console.log(X('https%3A%2F%2Fctbpsp.com%2Fcutominfoapi%2Frecommand%2Ftype%2F5%2Fpagesize%2F10%2Fcurrentpage%2F1%3Fprovince%3D%26industry%3D'))
        //拼接字符串
const Qa  =  new Date().getTime()
const Qb  =  X('https%3A%2F%2Fctbpsp.com%2Fcutominfoapi%2Frecommand%2Ftype%2F5%2Fpagesize%2F10%2Fcurrentpage%2F1%3Fprovince%3D%26industry%3D')



console.log(`${Qb}|0|${Qa}|1`);